### PR TITLE
changes for ros2

### PR DESCRIPTION
**Pull request by SammyRamone**
## Proposed changes
ROS 2

## Related issues
#15 

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

### CODE REVIEW

**Comment by ijnek** [comment]
Would be good to merge this one in when ready.

**Comment by SammyRamone** [comment]
It is now finished in my opinion. I tested it and it works. Can be merged, pls review

**Comment by ijnek** [comment]
@SammyRamone I'm not quite sure why the CI tests aren't running, would you be able to rebase this branch onto most recent master to see if they run?

Edit: I've rebased and put up another PR #22.

**Comment by SammyRamone** [comment]
So we can close this one right?

**Comment by ijnek** [comment]
Correct @SammyRamone

**Pull request closed without merging**
